=== juanma785/Examen-LGMST-UDT4/Examen de Lenguaje de Marca tema 4/Ejercicio 1/pedido.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pedido">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sucursal">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigo" type="xs:string" fixed="8"/>
              <xs:element name="nombreTrabajador" type="xs:string"/>
              <xs:element name="fecha" type="xs:date"/>
              <xs:element name="observaciones" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="articulo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigo" type="xs:string"/>
              <xs:element name="unidades" type="xs:integer"/>
              <xs:element name="precio" type="xs:float"/>
              <xs:element name="observaciones" type="xs:string" minOccurs="0"/>
              <xs:element name="plazoRevision" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== juanma785/Examen-LGMST-UDT4/Examen de Lenguaje de Marca tema 4/Ejercicio 1/pedido_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="pedido.xsd">
    <sucursal>
      <codigo>F5948394</codigo>
      <nombreTrabajador>Alejandro Sanz</nombreTrabajador>
      <fecha>2022-12-01</fecha>
      <observaciones>Urgente</observaciones>
    </sucursal>

    <articulo>
      <codigo>DMC-934</codigo>
      <unidades>10</unidades>
      <precio>5.0</precio>
      <observaciones> Incompleto</observaciones>
      <plazoRevision>9</plazoRevision>
    </articulo>

    <articulo>
      <codigo>PXK-024</codigo>
      <unidades>20</unidades>
      <precio>3.5</precio>
      <observaciones>Urgente</observaciones>
      <plazoRevision>3</plazoRevision>
    </articulo>
  </pedido>
